# Generated by Django 5.0.4 on 2024-04-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoCategoria',
            new_name='Planeta',
        ),
        migrations.AlterModelOptions(
            name='planeta',
            options={'verbose_name': 'descripcion de planetas', 'verbose_name_plural': 'descripciones de planetas'},
        ),
    ]
