# Generated by Django 5.0.4 on 2024-04-18 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planeta',
            options={'verbose_name_plural': 'planetas'},
        ),
        migrations.AlterField(
            model_name='personaje',
            name='planeta_origen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaje.planeta', verbose_name='planeta de origen'),
        ),
        migrations.AlterField(
            model_name='planeta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='planeta'),
        ),
    ]
