# Generated by Django 5.0.4 on 2024-04-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0002_alter_pais_options_alter_cliente_pais_origen_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planeta',
            options={'verbose_name_plural': 'planeta'},
        ),
    ]
