# Generated by Django 5.0.4 on 2024-04-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0003_alter_planeta_options'),
        ('planeta', '0002_rename_productocategoria_planeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='planeta_origen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeta.planeta', verbose_name='planeta de origen'),
        ),
        migrations.DeleteModel(
            name='Planeta',
        ),
    ]
